In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../airbnb/Airbnb_Open_Data.csv')

/var/folders/cz/bmrbdd0d2kq08ttprs_7dftr0000gn/T/ipykernel_75336/2937942561.py:1: DtypeWarning: Columns (0: license) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../airbnb/Airbnb_Open_Data.csv')

In [3]:
df.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [4]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  str
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  str
 4   host name                       102193 non-null  str
 5   neighbourhood group             102570 non-null  str
 6   neighbourhood                   102583 non-null  str
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  str
 10  country code                    102468 non-null  str
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  str
 13  room type                       102599 non-null  str
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  str
 16  service fee                     102326 non-null  str
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   str
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   str
 25  license                         2 non-null       str
dtypes: float64(9), int64(2), object(1), str(14)
memory usage: 46.7+ MB

In [6]:
columns_to_keep = ['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']
columns_to_drop = ['reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license','id']

In [7]:
df = df[columns_to_keep]

- Renaming the columns
- Droping duplicates
- Cleaning individual columns
- Remove the null values from the dataset
- Check for some more Transformation

In [8]:
df.columns

Index(['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='str')

In [9]:
df.rename(columns={'NAME':'name'})

,name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [10]:
df.columns = df.columns.str.lower().str.replace(' ','_')

In [11]:
df

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [12]:
#remove duplicates values

In [13]:
df.duplicated().value_counts()

False    102058
True        541
Name: count, dtype: int64

In [14]:
df.duplicated().sum()

np.int64(541)

In [15]:
df[df.duplicated()]

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review
102058,Master Bedroom with private Bathroom & Balcony,55110690425,unconfirmed,UZeyir,Queens,Maspeth,40.74056,-73.90635,United States,US,True,strict,Private room,2016.0,$706,$141,1.0,1.0,11/14/2021
102059,Cozy 2 br in sunny Fort Greene apt,80193772189,verified,Sally,Brooklyn,Fort Greene,40.68701,-73.97555,United States,US,False,flexible,Private room,2020.0,$651,$130,3.0,38.0,11/13/2021
102060,Duplex w/ Terrace @ Box House Hotel,72991962259,verified,The Box House Hotel,Brooklyn,Greenpoint,40.73756,-73.95350,United States,US,False,strict,Hotel room,2016.0,$907,$181,3.0,10.0,11/13/2021
102061,"Cozy, clean Greenpoint room with yard access",74975156081,verified,Dawn,Brooklyn,Greenpoint,40.72516,-73.95004,United States,US,False,strict,Private room,2013.0,$589,$118,30.0,38.0,11/13/2021
102062,2BR XL Loft: Cleaning CDC guidelines implemented,85844415221,unconfirmed,Vida,Brooklyn,Greenpoint,40.72732,-73.94185,United States,US,False,flexible,Entire home/apt,2015.0,$356,$71,30.0,13.0,11/13/2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [16]:
df = df.drop_duplicates()

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
#remove the nan value from the dataset

In [19]:
df.isnull().sum()

name                        250
host_id                       0
host_identity_verified      289
host_name                   404
neighbourhood_group          29
neighbourhood                16
lat                           8
long                          8
country                     532
country_code                131
instant_bookable            105
cancellation_policy          76
room_type                     0
construction_year           214
price                       247
service_fee                 273
minimum_nights              400
number_of_reviews           183
last_review               15832
dtype: int64

In [20]:
df[df.last_review.isnull()]

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
20,Huge 2 BR Upper East Cental Park,79805143117,verified,Audrey,Manhattan,East Harlem,40.79685,-73.94872,United States,NaN,NaN,moderate,Entire home/apt,2013.0,$281,$56,7.0,0.0,NaN
27,Magnifique Suite au N de Manhattan - vue Cloitres,38811420224,verified,Adrianna,Manhattan,Inwood,40.86754,-73.92639,United States,NaN,NaN,strict,Private room,2017.0,$274,$55,4.0,0.0,NaN
37,Clean and Quiet in Brooklyn,26207748876,verified,Arthur,Brooklyn,Bedford-Stuyvesant,40.68876,-73.94312,United States,US,False,moderate,Private room,2004.0,$203,$41,60.0,0.0,NaN
39,Country space in the city,49725315867,verified,Deanna,Brooklyn,Flatbush,40.63702,-73.96327,United States,US,True,strict,Private room,2011.0,"$1,020",$204,1.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102035,rooms in sunny Loft right off the Bedford L stop,6043744134,verified,Anna,Brooklyn,Williamsburg,40.71612,-73.95983,United States,US,True,strict,Private room,2009.0,$138,NaN,22.0,0.0,NaN
102037,Bx Apartment,11038605149,unconfirmed,Vii,Bronx,Olinville,40.88438,-73.86397,United States,US,True,strict,Private room,2008.0,$531,NaN,1.0,0.0,NaN
102045,Private Bedroom in Rego Park / Forest Hills,15978912806,unconfirmed,NaN,Queens,Rego Park,40.72460,-73.85688,United States,US,False,moderate,Private room,2006.0,NaN,NaN,1.0,0.0,NaN
102051,"A cozy getaway, home away from home",55697801194,verified,Isaiah,Brooklyn,East New York,40.66130,-73.89088,United States,US,True,moderate,Private room,NaN,$147,NaN,1.0,0.0,NaN
102056,Room & private bathroom in historic Harlem,15593031571,unconfirmed,Shireen,Manhattan,Harlem,40.81248,-73.94317,United States,US,True,strict,Private room,NaN,$848,NaN,2.0,0.0,NaN

In [21]:
df[df['number_of_reviews'] == 0]['last_review'].isnull().sum()

np.int64(15673)

### near 99% was null when number of review was 0. No reviews were done. data did not loss of data

In [22]:
df['last_review'] = pd.to_datetime(df['last_review'])

In [23]:
df['last_review'].dtype

dtype('<M8[us]')

In [24]:
df.loc[df['number_of_reviews'] == 0,'last_review'] = pd.NaT

In [25]:
df.sample(7)

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review
1028,Gorgeous ! Best Location in NYC !,21668537709,verified,Lynda,Manhattan,Upper West Side,40.77995,-73.98342,United States,US,False,moderate,Private room,2010.0,$764,$153,30.0,27.0,2017-08-11
101534,Fully furnished room on 110th St Broadway for ...,68946396234,unconfirmed,Ankit,Manhattan,Morningside Heights,40.80437,-73.96387,United States,US,True,flexible,Shared room,2008.0,$275,$55,1.0,0.0,NaT
86990,"Private bedroom in 2 bedroom, 2 bath- apartment",96729248606,unconfirmed,Joshua,Brooklyn,Midwood,40.62710,-73.97182,United States,US,True,moderate,Private room,2009.0,$948,$190,3.0,3.0,2017-07-30
76373,Beautiful Private Room near Columbia University,41687056715,verified,Gabriel,Manhattan,Morningside Heights,40.80751,-73.96619,United States,US,True,moderate,Private room,2016.0,$987,$197,2.0,5.0,2017-09-15
67090,Plaza Room for Rent Private Entrance Outdoor S...,69653023037,verified,Renee,Manhattan,Harlem,40.80383,-73.94965,United States,US,False,flexible,Entire home/apt,2020.0,$440,$88,180.0,6.0,2020-07-27
25618,Prime Midtown Location - Near Tourist Locations,44279755189,unconfirmed,NaN,Manhattan,Midtown,40.75257,-73.96853,United States,US,False,moderate,Entire home/apt,2014.0,$235,$47,1.0,0.0,NaT
61915,Monthly stays @ Murray Hill /2 bedrooms 1 bath...,15305325079,verified,Daia,Manhattan,Murray Hill,40.74700,-73.97636,United States,US,False,flexible,Entire home/apt,2020.0,"$1,103",$221,30.0,1.0,2021-12-01

In [26]:
df['last_review'].isnull().sum()

np.int64(15832)

In [27]:
df.isnull().sum()

name                        250
host_id                       0
host_identity_verified      289
host_name                   404
neighbourhood_group          29
neighbourhood                16
lat                           8
long                          8
country                     532
country_code                131
instant_bookable            105
cancellation_policy          76
room_type                     0
construction_year           214
price                       247
service_fee                 273
minimum_nights              400
number_of_reviews           183
last_review               15832
dtype: int64

In [28]:
df.dropna(subset = ['name'], inplace = True)

In [29]:
df.isnull().sum()

name                          0
host_id                       0
host_identity_verified      277
host_name                   398
neighbourhood_group          27
neighbourhood                16
lat                           8
long                          8
country                     527
country_code                123
instant_bookable             97
cancellation_policy          71
room_type                     0
construction_year           205
price                       244
service_fee                 273
minimum_nights              394
number_of_reviews           182
last_review               15796
dtype: int64

In [30]:
df[df['host_identity_verified'].isnull()]

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaT
6,BlissArtsSpace!,61300605564,NaN,Alberta,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2015.0,$71,$14,45.0,49.0,2017-10-05
19,Hip Historic Brownstone Apartment with Backyard,72145018858,NaN,Martin,Brooklyn,Crown Heights,40.67592,-73.94694,United States,NaN,NaN,moderate,Entire home/apt,2004.0,"$1,095",NaN,3.0,53.0,2019-06-22
23,CBG Helps Haiti Room#2.5,87668933180,NaN,William,Brooklyn,Park Slope,40.67989,-73.97798,United States,NaN,NaN,moderate,Private room,2017.0,"$1,050",$210,1.0,39.0,2019-01-01
25,"MAISON DES SIRENES1,bohemian apartment",48387947293,NaN,Miranda,Brooklyn,Bedford-Stuyvesant,40.68371,-73.94028,United States,NaN,NaN,strict,Entire home/apt,2006.0,"$1,175",$235,2.0,88.0,2019-06-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96336,Ma-Don Hideaway,73975905498,NaN,Lillie & Donald,Brooklyn,Bedford-Stuyvesant,40.69069,-73.92651,United States,US,True,moderate,Entire home/apt,2017.0,"$1,092",$218,2.0,13.0,2019-01-02
96337,Gorgeous room in luxury apartment (2),50042663518,NaN,Jelani,Brooklyn,Clinton Hill,40.68697,-73.96063,United States,US,False,moderate,Private room,2005.0,$536,$107,3.0,10.0,2019-06-05
96338,The Yorkville Gem,16811944489,NaN,Janine,Manhattan,Upper East Side,40.78023,-73.95069,United States,US,False,flexible,Shared room,2003.0,$320,$64,7.0,15.0,2019-07-01
96339,1940's Historic Brooklyn Townhome,73143337197,NaN,Mark,Brooklyn,East Flatbush,40.63863,-73.93826,United States,US,False,moderate,Entire home/apt,2012.0,$597,$119,5.0,2.0,2019-06-19
96340,"Sunny, CENTRAL Williamsburg Room with Rooftop",6659859418,NaN,Samantha,Brooklyn,Williamsburg,40.71446,-73.95992,United States,US,False,flexible,Private room,2015.0,$297,$59,1.0,4.0,2018-08-13

In [31]:
df.sample(10)

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review
80238,PEACE AND TRANQUILITY,94270231525,verified,Pauline,Bronx,Baychester,40.87192,-73.84676,United States,US,True,moderate,Private room,2022.0,$839,$168,1.0,0.0,NaT
71947,Spacious Chelsea Penthouse w/roof!,52999473471,unconfirmed,Kevin,Manhattan,Chelsea,40.74212,-73.99828,United States,US,False,strict,Private room,2020.0,$295,$59,2.0,20.0,2016-09-01
4189,Cozy & modern 1 br apt in Brooklyn,83515409751,verified,Herby,Brooklyn,Prospect-Lefferts Gardens,40.65820,-73.95688,United States,US,False,strict,Entire home/apt,2021.0,$750,$150,30.0,3.0,2018-03-02
7365,CHARMING NYC Studio Loft NEAR SOHO!,52325967620,unconfirmed,O,Manhattan,Greenwich Village,40.72937,-74.00125,United States,US,True,strict,Entire home/apt,2016.0,$810,$162,30.0,43.0,2019-01-25
8096,Orange Room,3117838491,verified,Memo & Iso,Brooklyn,Bedford-Stuyvesant,40.68549,-73.93532,United States,US,True,strict,Private room,2019.0,$762,$152,1.0,163.0,2019-06-18
17498,Cosy flat West Village,31957905284,unconfirmed,Xavier,Manhattan,West Village,40.73316,-74.00183,United States,US,True,strict,Entire home/apt,2004.0,$989,$198,2.0,9.0,2018-05-12
15662,Quiet room in Bed-Stuy,60659545477,verified,Joseph,Brooklyn,Bedford-Stuyvesant,40.69186,-73.94038,United States,US,True,moderate,Private room,2014.0,$154,$31,80.0,0.0,NaT
64016,Exclusive Standard Accommodation at Times SQ H...,69957923637,unconfirmed,Blake,Manhattan,Theater District,40.76153,-73.98664,United States,US,True,flexible,Private room,2009.0,$447,$89,1.0,4.0,2021-09-06
79964,Private Room in Homey Roosevelt Island Apartment,53773634141,verified,Kate,Manhattan,Roosevelt Island,40.76208,-73.94954,United States,US,False,moderate,Private room,2017.0,$499,$100,2.0,85.0,2019-06-30
94966,"Lovely room with private terrace, ensuite",67932103374,unconfirmed,Devon,Manhattan,East Village,40.72561,-73.97622,United States,US,False,flexible,Private room,2012.0,$615,$123,1.0,41.0,2019-05-17

### nothing find to recover the null value of `host_identity_verified` so i've to drop the null value

In [32]:
df.dropna(subset=['host_identity_verified'], inplace = True)

In [33]:
df.isnull().sum()

name                          0
host_id                       0
host_identity_verified        0
host_name                   397
neighbourhood_group          20
neighbourhood                16
lat                           8
long                          8
country                     527
country_code                119
instant_bookable             93
cancellation_policy          71
room_type                     0
construction_year           193
price                       240
service_fee                 272
minimum_nights              385
number_of_reviews           182
last_review               15756
dtype: int64

#### host name is not replaceable by any data so i've to drop nan value of this column

In [34]:
df.dropna(subset=['host_name'], inplace = True)

In [35]:
df.isnull().sum()

name                          0
host_id                       0
host_identity_verified        0
host_name                     0
neighbourhood_group          19
neighbourhood                16
lat                           8
long                          8
country                     526
country_code                118
instant_bookable             92
cancellation_policy          70
room_type                     0
construction_year           188
price                       235
service_fee                 267
minimum_nights              385
number_of_reviews           182
last_review               15677
dtype: int64

In [36]:
df.dropna(subset=['neighbourhood_group','neighbourhood','lat','long'], inplace = True)

In [37]:
df.isnull().sum()

name                          0
host_id                       0
host_identity_verified        0
host_name                     0
neighbourhood_group           0
neighbourhood                 0
lat                           0
long                          0
country                     523
country_code                115
instant_bookable             89
cancellation_policy          67
room_type                     0
construction_year           186
price                       233
service_fee                 267
minimum_nights              384
number_of_reviews           182
last_review               15674
dtype: int64

In [38]:
df[df['country'].isnull()]

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review
156,"Sunny, clean 1 bdrm in W. Village",75987317883,verified,James,Manhattan,West Village,40.73226,-74.00401,NaN,NaN,NaN,NaN,Entire home/apt,2018.0,$738,$148,45.0,134.0,NaT
157,Great location in Williamsburg,51756716507,unconfirmed,Roman,Brooklyn,Williamsburg,40.71363,-73.96398,NaN,NaN,NaN,NaN,Entire home/apt,2007.0,"$1,013",$203,6.0,27.0,NaT
158,Light and Airy Upper East Side 1 BDR apartment,30351473270,unconfirmed,Kellan,Manhattan,Upper East Side,40.77711,-73.95270,NaN,NaN,NaN,NaN,Entire home/apt,2004.0,$464,$93,4.0,126.0,NaT
159,Luxury Brownstone in Boerum Hill,22525653405,unconfirmed,Owen,Brooklyn,Boerum Hill,40.68559,-73.98094,NaN,NaN,NaN,NaN,Entire home/apt,2006.0,$744,$149,3.0,23.0,NaT
160,CENTRAL PARK LOFT all for YOU,82585795978,verified,Eddy,Manhattan,Upper East Side,40.77456,-73.95323,NaN,NaN,NaN,NaN,Entire home/apt,2014.0,$764,$153,1.0,234.0,2019-06-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101368,Charming Park Slope Apt (fits up to 6 ppl)!,2778317625,unconfirmed,Julia,Brooklyn,Windsor Terrace,40.66063,-73.98348,NaN,US,False,moderate,Entire home/apt,2004.0,$765,$153,3.0,0.0,NaT
101369,Studio with amazing view,25057683830,unconfirmed,Carolann,Manhattan,Financial District,40.70588,-74.01590,NaN,US,True,strict,Entire home/apt,2010.0,$201,$40,300.0,0.0,NaT
101370,Private apartment in new Brooklyn building!,35509233859,unconfirmed,Steven & Melissa,Brooklyn,Bedford-Stuyvesant,40.68438,-73.95299,NaN,US,False,strict,Entire home/apt,2019.0,$132,$26,2.0,33.0,2019-05-22
101371,UES(mini loft)Clean flex room (Female Only),76384585618,verified,Eun M,Manhattan,Upper East Side,40.77759,-73.95321,NaN,US,False,strict,Private room,2022.0,$940,$188,1.0,133.0,2019-06-19
101372,Luxury Loft in Williamsburg,5156600288,verified,Aaron,Brooklyn,Williamsburg,40.71218,-73.96048,NaN,US,False,strict,Entire home/apt,2020.0,"$1,020",$204,3.0,8.0,2018-08-26

In [39]:
df.country_code.unique()

<ArrowStringArray>
['US', nan]
Length: 2, dtype: str

In [40]:
# if there exist different country, but here just one country exist
df.loc[(df['country_code'] == 'US') & (df['country'].isnull()),'country'] = 'United States'

In [41]:
df.isnull().sum()

name                          0
host_id                       0
host_identity_verified        0
host_name                     0
neighbourhood_group           0
neighbourhood                 0
lat                           0
long                          0
country                      79
country_code                115
instant_bookable             89
cancellation_policy          67
room_type                     0
construction_year           186
price                       233
service_fee                 267
minimum_nights              384
number_of_reviews           182
last_review               15674
dtype: int64

In [42]:
df['country'].unique()

<ArrowStringArray>
['United States', nan]
Length: 2, dtype: str

In [43]:
# fill with United states 
df['country'] = df['country'].fillna('United States')

In [44]:
df.loc[(df['country'] == 'United States') & (df['country_code'].isnull()), 'country_code'] = 'US'

In [45]:
df.isnull().sum()

name                          0
host_id                       0
host_identity_verified        0
host_name                     0
neighbourhood_group           0
neighbourhood                 0
lat                           0
long                          0
country                       0
country_code                  0
instant_bookable             89
cancellation_policy          67
room_type                     0
construction_year           186
price                       233
service_fee                 267
minimum_nights              384
number_of_reviews           182
last_review               15674
dtype: int64

In [46]:
df.dropna(subset=['instant_bookable', 'cancellation_policy','construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews'], inplace = True)

In [47]:
df.isnull().sum()

name                          0
host_id                       0
host_identity_verified        0
host_name                     0
neighbourhood_group           0
neighbourhood                 0
lat                           0
long                          0
country                       0
country_code                  0
instant_bookable              0
cancellation_policy           0
room_type                     0
construction_year             0
price                         0
service_fee                   0
minimum_nights                0
number_of_reviews             0
last_review               15408
dtype: int64

In [48]:
df.head()

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,2021-10-19
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,2022-05-21
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,2018-11-19
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0,2019-06-22
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0,2017-10-05

#### Remove `$` and `,` sign from `price` and `service_fee` columns

In [49]:
df['price'] = df['price'].str.replace('[$,]','',regex=True).astype(float)

In [50]:
df['service_fee'].str.replace('$','', regex=False).astype(float).max()

240.0

In [51]:
df['service_fee'] = df['service_fee'].str.replace('$','', regex=False).astype(float)

In [52]:
df[['price','service_fee']]

         price  service_fee
0        966.0        193.0
1        142.0         28.0
4        204.0         41.0
5        577.0        115.0
7       1060.0        212.0
...        ...          ...
102029   822.0        164.0
102030   455.0         91.0
102031  1078.0        216.0
102032   103.0         21.0
102040   982.0        196.0

[99812 rows x 2 columns]

In [53]:
df.head()

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,966.0,193.0,10.0,9.0,2021-10-19
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,142.0,28.0,30.0,45.0,2022-05-21
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,204.0,41.0,10.0,9.0,2018-11-19
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,577.0,115.0,3.0,74.0,2019-06-22
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,1060.0,212.0,45.0,49.0,2017-10-05

In [54]:
df['construction_year'] = df['construction_year'].astype(int)

In [55]:
df['minimum_nights'].min() #maybe wrong data entry problem fixed it by make absolute value

-1223.0

In [56]:
df[df['minimum_nights']<0]

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review
176,BROOKLYN VICTORIAN STYLE SUITE.....,83631499592,unconfirmed,Frederick,Brooklyn,Fort Greene,40.69098,-73.97113,United States,US,False,flexible,Private room,2008,1155.0,231.0,-10.0,213.0,2019-06-24
398,SUPER BIG AND COZY PRIVATE BEDROOM,50336791874,verified,Tucker,Brooklyn,Kensington,40.64302,-73.97255,United States,US,False,flexible,Private room,2015,779.0,156.0,-1.0,82.0,2019-05-19
421,Charming Nolita Apartment!!,7389895192,verified,Belinda,Manhattan,Nolita,40.72094,-73.99706,United States,US,False,flexible,Entire home/apt,2008,874.0,175.0,-10.0,68.0,2019-06-10
441,Cozy apartment in a brownstone,81186886194,verified,Adelaide,Manhattan,Harlem,40.80497,-73.95016,United States,US,False,moderate,Entire home/apt,2021,920.0,184.0,-12.0,203.0,2019-07-06
478,Charming upper west side apartment,89878315253,unconfirmed,Alen,Manhattan,Upper West Side,40.77886,-73.98042,United States,US,True,strict,Entire home/apt,2022,410.0,82.0,-2.0,129.0,2019-06-07
525,Chateau Style Brooklyn Loft for Singles or Cou...,2631536622,verified,Carlos,Brooklyn,Bedford-Stuyvesant,40.68967,-73.95445,United States,US,False,moderate,Entire home/apt,2022,413.0,83.0,-3.0,42.0,2019-05-18
42446,"Cozy room in bright, spacious apartment",84040511136,verified,Steven,Bronx,Hunts Point,40.81731,-73.89052,United States,US,False,moderate,Private room,2003,1200.0,240.0,-1223.0,0.0,NaT
42500,2bd BOUTIQUE Apartament in the heart of MANHA...,2679070022,unconfirmed,Tom,Manhattan,Hell's Kitchen,40.76694,-73.98773,United States,US,True,flexible,Entire home/apt,2009,711.0,142.0,-365.0,13.0,2019-07-07
42538,Newly Renovated Garden Apartment,98469733112,verified,Margie,Brooklyn,Bedford-Stuyvesant,40.68470,-73.94350,United States,US,True,moderate,Entire home/apt,2022,85.0,17.0,-200.0,3.0,2019-04-23
69749,Amazing location! 10ft from L train,62132542936,verified,Giorgia & Benjamin,Brooklyn,Williamsburg,40.71534,-73.94906,United States,US,False,moderate,Private room,2012,328.0,66.0,-125.0,146.0,2019-06-23
91271,Beautiful modern & large 2 bedroom,13861414317,unconfirmed,Vikas,Manhattan,Midtown,40.74433,-73.98318,United States,US,False,moderate,Entire home/apt,2007,772.0,154.0,-10.0,0.0,NaT
91357,Cozy Brooklyn Apartment,63988893317,verified,Daniella,Brooklyn,Gowanus,40.67070,-73.99118,United States,US,True,moderate,Shared room,2014,1177.0,235.0,-10.0,9.0,2017-05-08

In [57]:
df['minimum_nights'].abs().max()   # look like outlier. capping it the upper value 30

5645.0

In [58]:
df['minimum_nights'] = df['minimum_nights'].abs()

In [59]:
df[df['minimum_nights'] > 30]

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009,1060.0,212.0,45.0,49.0,2017-10-05
37,Clean and Quiet in Brooklyn,26207748876,verified,Arthur,Brooklyn,Bedford-Stuyvesant,40.68876,-73.94312,United States,US,False,moderate,Private room,2004,203.0,41.0,60.0,0.0,NaT
82,Spacious luminous apt Upper West NYC,97798221815,verified,Alisa,Manhattan,Harlem,40.82915,-73.95136,United States,US,True,flexible,Entire home/apt,2005,1056.0,211.0,31.0,54.0,2019-03-23
164,Luxurious Condo in DUBMO with View,20270952150,unconfirmed,Edith,Brooklyn,DUMBO,40.70207,-73.98571,United States,US,True,strict,Private room,2016,385.0,77.0,47.0,14.0,2021-04-25
165,Charming & Cozy midtown loft any WEEK ENDS !!!,3310140241,verified,Luke,Manhattan,Upper East Side,40.76123,-73.96420,United States,US,False,flexible,Entire home/apt,2021,950.0,190.0,81.0,4.0,2016-09-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101667,Charming 1 Bedroom in center of East Village,74880950520,unconfirmed,Anna,Manhattan,East Village,40.72645,-73.98591,United States,US,True,strict,Entire home/apt,2021,1098.0,220.0,90.0,28.0,2019-04-30
101796,Small Cozy Room in Herald Square,68953119258,verified,Chelsea,Manhattan,Midtown,40.75001,-73.98629,United States,US,False,moderate,Private room,2019,449.0,90.0,300.0,1.0,2017-03-25
101842,Beautiful duplex in Gramercy,89855789531,unconfirmed,Pilar,Manhattan,Gramercy,40.73746,-73.98338,United States,US,True,strict,Entire home/apt,2013,1120.0,224.0,120.0,2.0,2017-08-13
101980,NYU/E.Village Cafes & Bars*6 month $3500/mo,61716466230,unconfirmed,Lisa,Manhattan,East Village,40.72804,-73.98665,United States,US,False,strict,Entire home/apt,2013,156.0,31.0,180.0,15.0,2019-05-28
102010,Brooklyn Style!,35669070960,unconfirmed,Tina,Brooklyn,Flatbush,40.64847,-73.96132,United States,US,False,strict,Entire home/apt,2020,232.0,46.0,31.0,2.0,2018-03-25

In [60]:
df['minimum_nights'].describe()

count    99812.000000
mean         8.120597
std         30.359856
min          1.000000
25%          2.000000
50%          3.000000
75%          5.000000
max       5645.000000
Name: minimum_nights, dtype: float64

In [61]:
df['minimum_nights'] = df['minimum_nights'].clip(upper=30)

In [62]:
df['minimum_nights'].describe()

count    99812.000000
mean         6.914640
std          9.734979
min          1.000000
25%          2.000000
50%          3.000000
75%          5.000000
max         30.000000
Name: minimum_nights, dtype: float64

In [63]:
df.head()

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020,966.0,193.0,10.0,9.0,2021-10-19
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007,142.0,28.0,30.0,45.0,2022-05-21
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009,204.0,41.0,10.0,9.0,2018-11-19
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013,577.0,115.0,3.0,74.0,2019-06-22
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009,1060.0,212.0,30.0,49.0,2017-10-05

In [64]:
df['price'].describe()

count    99812.000000
mean       625.364385
std        331.638541
min         50.000000
25%        340.000000
50%        624.000000
75%        913.000000
max       1200.000000
Name: price, dtype: float64

In [65]:
df['number_of_reviews'].describe()

count    99812.000000
mean        27.366529
std         49.322255
min          0.000000
25%          1.000000
50%          7.000000
75%         30.000000
max       1024.000000
Name: number_of_reviews, dtype: float64

In [66]:
df.head()

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020,966.0,193.0,10.0,9.0,2021-10-19
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007,142.0,28.0,30.0,45.0,2022-05-21
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009,204.0,41.0,10.0,9.0,2018-11-19
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013,577.0,115.0,3.0,74.0,2019-06-22
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009,1060.0,212.0,30.0,49.0,2017-10-05

In [67]:
df['neighbourhood_group'].unique()

<ArrowStringArray>
['Brooklyn', 'Manhattan', 'brookln', 'Queens', 'Staten Island', 'Bronx']
Length: 6, dtype: str

#### here Brooklyn and brookln are the same, replce brookln by Brooklyn

In [68]:
df['neighbourhood_group'] = df['neighbourhood_group'].replace('brookln','Brooklyn')

In [69]:
df['neighbourhood_group'].unique()

<ArrowStringArray>
['Brooklyn', 'Manhattan', 'Queens', 'Staten Island', 'Bronx']
Length: 5, dtype: str

In [70]:
df['neighbourhood'].value_counts()

neighbourhood
Bedford-Stuyvesant        7722
Williamsburg              7550
Harlem                    5302
Bushwick                  4856
Hell's Kitchen            3885
                          ...
Willowbrook                  3
Gerritsen Beach              3
Fort Wadsworth               2
Glen Oaks                    2
Chelsea, Staten Island       1
Name: count, Length: 224, dtype: int64

In [71]:
df['room_type'].unique()

<ArrowStringArray>
['Private room', 'Entire home/apt', 'Shared room', 'Hotel room']
Length: 4, dtype: str

In [72]:
df['cancellation_policy'].unique()

<ArrowStringArray>
['strict', 'moderate', 'flexible']
Length: 3, dtype: str

In [73]:
df['instant_bookable'].unique()

array([False, True], dtype=object)

In [74]:
df['instant_bookable'] = df['instant_bookable'].apply(lambda x: 1 if x == True else 0)

In [75]:
df.head()

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020,966.0,193.0,10.0,9.0,2021-10-19
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007,142.0,28.0,30.0,45.0,2022-05-21
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009,204.0,41.0,10.0,9.0,2018-11-19
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013,577.0,115.0,3.0,74.0,2019-06-22
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009,1060.0,212.0,30.0,49.0,2017-10-05

In [76]:
df.to_csv('airbnb_cleaned.csv', index = False)